### ISSUE TITLE
[FAQ] About Windows 7

### ISSUE THREAD

**Issue by westside** [bhaptics/haptic-library#100]
* Q: i am going to ask about the version of bHaptics Player .  I have to install the driver in
Window7 without updating the version of window.
As i have found that the minimum of system requirement of your
official VR game "Hell Breaker is Window7, i suppose that the bhaptics
haptic suit can be used in Window 7 too.So would you have the version
to support Windows 7? If yes, please send me a link to download it. If
not, would you give me any suggestion to do that?

* A:  Hell breaker can be running in Windows 7 but not the bhaptics player because Bluetooth LE is not supported in Windows 7. Please use the latest Windows 10 version for experiencing full support of our latest features.

**Comment by YOYO-WONG-dev** [comment]
As my client is using Window 7 and they don't want to update to Window 8.1 or above, do you have any suggestion to use bhaptics in Window 7 ?

**Comment by westside** [comment]
Technically It will be possible using a proxy program which bypass the message  from windows 7  to the other computer, but we don't support it officially. 
Sorry for your inconvenience.

**Comment by YOYO-WONG-dev** [comment]
As i have never used proxy program ,so would you give me some references or examples or demos about proxy program?

**Comment by westside** [comment]
Please check this https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
I'm not sure nginx will work with Windows 7, but you can check the brief concept here.

**Comment by YOYO-WONG-dev** [comment]
Thank you for your recommendation.  Have you ever installed bhaptics player in window 7 ?
As the connection needs bluetooth, after bypassing the message, would the bluetooth work?

**Comment by westside** [comment]
I haven't tested in Windows 7 because we don't have any PC with Windows 7.
The concept is like this. 

![image](https://user-images.githubusercontent.com/1837913/72309334-0b569380-36c2-11ea-8edc-172f6d8fee38.png)

You can get cheap windows 10 devices around $6~70.
I cannot guarantee anything about Windows 7.
