### ISSUE TITLE
Bhaptics version 1.5.5

### ISSUE THREAD

**Issue by karevana** [bhaptics/haptic-library#102]
I just got the latest version 1.5.5 via auto update 
Now my arms dont work  tried music  and only vest works... the arms are paired.and provide feedback.
When I click on music a new screen designer2.com pops up
Looks like the arms are not mapped. so, I tried to login but it just circles so I cant modify it. 

The arms for music are the best, I used to use music melody but not working please help,

Thanks 
Karen

**Comment by westside** [comment]
Hello Karen, 

We are going to fix that and release it soon, and let you know here. 

Sorry for your inconvenience.

**Comment by westside** [comment]
We've updated the bhaptics player.
Please check our latest player.

**Comment by karevana** [comment]
Thanks, it's working now
