### ISSUE TITLE
[Unity-Android] build can't connect through bluetooth.

### ISSUE THREAD

**Issue by djonczak** [bhaptics/haptic-library#113]
Hi, I was trying to use your bHaptics SDK for Unity to connect to ThermoReal and use it in game, but after making test build (I have tried build for Android and for Oculus Quest, GO) and those have problem with connecting to it ( I used bHaptics Player on Android and it didn't have problem with connecting to ThermoReal). 
After some debugging, I have found that build is unable to find haptic_library, so maybe this is causing problem with connecting via bluetooth.

**Comment by westside** [comment]
We don't support the ThermoReal device in android officially. 
Please contact to Themoreal first.
