### ISSUE TITLE
Cannot use the  bHaptics Designer website

### ISSUE THREAD

**Issue by siqiyaoyao** [bhaptics/haptic-library#126]
Hi, 

I am a bhaptic user. I have the problem of log in to the bHaptics Designer website.  When I clicked the active link like the following, the information always showed "Error encountered". When I tried to use FB account to login in, the web always failed. Could you tell me how to use the bHaptics Designer website?

Best,

**Comment by westside** [comment]
Sorry for the late response.
Did you solve the problem?
