### ISSUE TITLE
haptic_labrary.dll not found...

### ISSUE THREAD

**Issue by itzikpel** [bhaptics/haptic-library#131]
Hi, 

The bHaptic plugin not working.. 
need help
thanks

![image](https://user-images.githubusercontent.com/5984972/94737107-f4ea8800-0375-11eb-879c-f8cc9666f28f.png)

**Comment by westside** [comment]
Really sorry for your inconvenience. 
Please install visual studio redistributable runtimes. https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads


This is related to this issue below.
https://github.com/bhaptics/haptic-library/issues/127

**Comment by itzikpel** [comment]
Thank you Sangwon
