### ISSUE TITLE
[Unity-Android] Garbage allocations and performance hit on android.

### ISSUE THREAD

**Issue by JonathanWouters** [bhaptics/haptic-library#143]
Hi,

I'm seeing a big performance drop when using bHaptics on android (v1.5.3 unity plugin).
The problems only happen when trying to play a haptic.

(screenshots from deep profiler)
![DeepProfileAndroid2](https://user-images.githubusercontent.com/16886522/107053063-b1de6c80-67ce-11eb-8305-68838b2d8c8c.png)

Problem seems to be on 2 locations, both doing a Json Parse which creates a lot of garbage and tanks performance.
2 Methods that show up in the profiler are AndroidHaptic.SubmitRegistered and BHapticsAndroidManager.OnChangeRequest.

![DeepProfileAndroid](https://user-images.githubusercontent.com/16886522/107053735-755f4080-67cf-11eb-92bd-1c932e58a3fb.png)

From what I can tell looking through the code.
if (!haptic.IsFeedbackRegistered(assetId)) seems not to work as intended since haptic.RegisterTactFileStr gets called every frame.
![image](https://user-images.githubusercontent.com/16886522/107054257-28c83500-67d0-11eb-85bc-ecf5fa9f0fde.png)

**Comment by SanghunK** [comment]
First of all, I'm sorry for your inconvenience, and thanks for the details.
We will fix this issue as soon as possible.

+As far as we know, turning off the profiler works well. It's not a perfect solution, but please refer to it.

**Comment by JonathanWouters** [comment]
> +As far as we know, turning off the profiler works well. It's not a perfect solution, but please refer to it.
I did see similar performance issues in release builds, without profiler.

Thanks for taking a look !
