### ISSUE TITLE
Is it possible to get battery level in C# Bhaptics.Tact?

### ISSUE THREAD

**Issue by pnuzhdin** [bhaptics/haptic-library#166]
Is it possible to get battery level in C# Bhaptics.Tact?

**Comment by westside** [comment]
We support HTTP api to access device information on Windows. 

Please refer this doc. https://github.com/bhaptics/haptic-library/wiki/HTTP-API-for-bHaptics-Player-(Windows-only)

**Comment by pnuzhdin** [comment]
Thanks, very useful, it works!
