### ISSUE TITLE
Haptic feedback isn't reproduced for the Vest first time Unity app is loaded but starts working after the game restarts

### ISSUE THREAD

**Issue by pnuzhdin** [bhaptics/haptic-library#169]
I am not sure on which side the issue is (Windows bHaptics Player 1.6.6 or 1.6.6, bHaptics Unity Plugin or TactSuitX40) but here it is:
1. Make sure bHaptics Player Start w/ Windows start up option is enabled and Vest is paired.
2. Reboot the PC.
3. Run Unity project with only `VestHapticClip.Play()` e.g. `clip.Play(intensity, duration, vestRotationAngleX, vestRotationOffsetY)`. Pay attention that we don't call `BhapticsManager.Init` because it's already done in `VestHapticClip.Play`, so the only bHaptics API we are using is the `Play` method of some `VestHapticClip`.
4. Observe: haptic feedback isn't reproduced. But at the same time, ping is working fine for the same Vest in bHaptics Player while the Unity project is running. So the Vest is working fine and communicating well with the bHaptics Player.
5. Stop the Unity project.
6. Run the same Unity project again.

Observe: Now haptic feedback is reproduced as expected. But the issue is reproduced again after the PC reboot.

**Comment by pnuzhdin** [comment]
There are no errors in the Unity log only `[bhaptics] Initialized.`

**Comment by SanghunK** [comment]
First of all, Sorry for your inconvenience and Thank you for the detailed explanation.

I have checked on this issue. is the same issue as the first PLAY of the GIF below?
![firstPlay](https://user-images.githubusercontent.com/18112611/120418457-898d0600-c39b-11eb-8b23-87f2dbdd42d6.gif)

**Comment by pnuzhdin** [comment]
Yep, but as I can see the issue isn't reproduced for you starting from the second "Play" without having to restart the game. For me, it's still reproducible for the second and the following "Play" and the only way to fix it is to restart the whole game. It might be a race condition so we might see different effects of the same issue.

**Comment by pnuzhdin** [comment]
Also, it might be helpful to reproduce the issue to use the fact that we don't "Play" the same clip. Actually, we select the random clip from the list of Vest clips and "Play" it. So the race condition is might be related to 
```
var haptic = BhapticsManager.GetHaptic();
            if (!haptic.IsFeedbackRegistered(assetId))
            {
                haptic.RegisterTactFileStr(assetId, JsonValue);
            }
```

**Comment by pnuzhdin** [comment]
And it seems it isn't reproducible on Android/Oculus Quest but I am not absolutely sure, just don't remember I saw it here.

**Comment by pnuzhdin** [comment]
Also, we are using Unity 2018.2.10f1 and bHaptics Haptic Plugin for Unity 1.5.7 in a case it's important.

**Comment by SanghunK** [comment]
ok, thanks! I will check that!
and.. if you have a lot of time, could you share the video or sample project? I'd really appreciate it if you could do that.

**Comment by SanghunK** [comment]
This issue has been resolved, so I will close it.
