### ISSUE TITLE
bHaptics Unity SDK examples without PathMode (only DotMode). 

### ISSUE THREAD

**Issue by MatiasBrunacci** [bhaptics/haptic-library#184]
Hi guys, I have a TactSuitx40 and I'm using Unity to try to replicate the PathMode interaction you have in the settings. I only programmed a DotMode interaction based on the examples you provided. 

Is there a chance to get a Unity example based on PathMode interactions?

https://user-images.githubusercontent.com/14755165/140336321-7a3b23ab-5bdf-44cf-9b7c-0b3b0524aeb8.mp4

This is the UI interaction I'm programming, as I said, it only works by clicking on each of the buttons individually (DotMode), but what I need is something closer to the video capture in settings I just uploaded before (PathMode). 

![Screenshot 2021-11-01 192558](https://user-images.githubusercontent.com/14755165/140336479-70a59792-8e41-4639-9e5c-a0e1559a466f.png)

**Comment by SanghunK** [comment]
First of all, thank you for asking me a question.
I updated what you wanted on 1.6.3a branch.
However, there is no line effect, so you make it using LineRenderer or somthing else.
Thank you!
