### ISSUE TITLE
Bluetooth pairing issue with Pico Neo3

### ISSUE THREAD

**Issue by KitamuraTsumiki** [bhaptics/haptic-library#199]
I tried to pair TactSuit with Pico Neo3 from the system Bluetooth menu, but it always failed to connect.
"tactot" is displayed on the Bluetooth device list. However, when I select this, the connection fails.

I understand that your company doesn't officially support pairing TactSuit with Pico Neo3,
But I have to integrate Tactsuit x16 with it in one of our business projects.

I guess that the version of the SDK is not so related, but the version used for testing is below;
1.5.0, 1.6.5

**Comment by westside** [comment]
I just tested our SDK with Pico Neo 2. 

1) Pair with bluetooth menu
2) Use our latest SDK

Works fine on our side. 
This should work without our bHaptics Player. 
https://www.oculus.com/experiences/quest/3454125161357542/

**Comment by westside** [comment]
@KitamuraTsumiki  Please update your Tactsuit in the bHaptics Player. 
![image](https://user-images.githubusercontent.com/1837913/150944380-18893dc1-585f-4837-890f-ce62c50ffe54.png)

**Comment by KitamuraTsumiki** [comment]
@westside Thank you for replying soon.
I will try again with the latest firmware and SDK.

**Comment by KitamuraTsumiki** [comment]
@westside It worked with the latest firmware and SDK! Thanks a lot!
