### ISSUE TITLE
Unity Plugin IsConnect is not correct

### ISSUE THREAD

**Issue by Yuuki-Ishimaru** [bhaptics/haptic-library#200]
Using the TactSuit X40, with Unity plugin version 1.6.5. 
IsConnect does not reflect the connectivity status when the device is turned off while game is running in editor.
Further, if queried in Unity and the device is turned off, the BHaptics app still says it is connected, and IsConnect remains true in subsequent executions.
When the vest is turned back on, it says connected through both the API and app, but no haptic reactions happen even if triggered, both via Unity API and Feedback test.

**Comment by SanghunK** [comment]
Hi. Yuuki. Thank you for let me know this issue.
I think, this issue seems to have been caused by an update to the performance issue.
We will fix it at the next update.

Until then, you can use a some trick to makt it works well.
1. Create a SimpleHapticClip and don't change the values from default values.(The point is that all motors have 0 intensity.)
![image](https://user-images.githubusercontent.com/18112611/155655302-9baffaa4-54a3-4d54-b477-891cdb50f063.png)
![image](https://user-images.githubusercontent.com/18112611/155655339-aaef6a13-de97-443c-897b-4d3502e95247.png)

2. Play the SimpleHapticClip before using IsConnect.
```C#
public SimpleHapticClip clip;

clip.Play();
Debug.Log(BhapticsManager.GetHaptic().IsConnect(HapticDeviceType.TactSuit));
```
Then, you can get correct connectivity status. Please let me know if this trick is not working.
Thank you.

**Comment by Yuuki-Ishimaru** [comment]
Also, is there a way to retrieve the connected device's serial number via the Unity API?

**Comment by SanghunK** [comment]
We have two kinds of number. One is the serial number, the other is the MAC address.
The serial number used to manage the device. The MAC address used to pair on your PC or VR devices.
Which one you want?

+ If you want to The serial number, the answer is NO. but the MAC is YES.

**Comment by Yuuki-Ishimaru** [comment]
Ah, yeah I was looking for the serial number. How might I go about doing that? The BHaptics app seems to be able to retrieve it...

**Comment by Yuuki-Ishimaru** [comment]
If not the serial number, how do I retrieve the MAC via the API?

**Comment by Yuuki-Ishimaru** [comment]
@SanghunK how do I retrieve the MAC via the API? Also when is the expected release for the connectivity status fix?

**Comment by westside** [comment]
@Yuuki-Ishimaru Sorry for the late response. 
We provide HTTP API for windows. 
Please refer this documentaion. https://github.com/bhaptics/haptic-library/wiki/HTTP-API-for-bHaptics-Player-(Windows-only)

**Comment by Yuuki-Ishimaru** [comment]
I'm on version 1.7.5, it still doesn't seem like the IsConnect is correct

**Comment by SanghunK** [comment]
Would you share me your test script and environment?

I tested on Unity 2020.3.28f1, Unity SDK version 1.6.6(latest), bHaptics Player v1.7.6(latest), and worked well.
And, this is my test script.
```C#
using UnityEngine;
using Bhaptics.Tact.Unity;

public class MyTestScript : MonoBehaviour
{
    private IHaptic haptic => BhapticsManager.GetHaptic();

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.A))
        {
            Debug.LogErrorFormat("IsConnect Vest: {0}", haptic.IsConnect(HapticDeviceType.TactSuit));
            Debug.LogErrorFormat("IsConnect Tal: {0}", haptic.IsConnect(HapticDeviceType.Tactal));
        }
    }
}
```

**Comment by Yuuki-Ishimaru** [comment]
Using unity 2020.1.3f1, BHaptics version 1.7.6.1.

I am using similar code for checking connectivity:
` private void Update()
        {
            ...
            print("Tact suit connected: " + BhapticsManager.GetHaptic().IsConnect(Bhaptics.Tact.Unity.HapticDeviceType.TactSuit));
            ...
         }
`

**Comment by SanghunK** [comment]
umm.. that's so weird.
This is a test result with your test code. I just have turned on & off my TactSuit X40
![IsConnect_test](https://user-images.githubusercontent.com/18112611/165667367-a8aaa863-e990-405a-afc7-f6c0de77b836.gif)
Just one check, you're saying you can't do this, right?
I'll keep trying to fix this issue. And, I think it would be helpful if you could share the sample project!

**Comment by Yuuki-Ishimaru** [comment]
Yes, currently I cannot do this.
Does firmware version matter at all?
I will attempt to reproduce it on a new scene

**Comment by SanghunK** [comment]
No, the firmware is not a problem as I know.
I will waiting for your sample project.
Thank you!

**Comment by Yuuki-Ishimaru** [comment]
I tested it on a sample project and it does not work. 
One thing I am noticing is that even when I shut off the vest, the applet does not show that the device was disconnected

**Comment by SanghunK** [comment]
Would you share the sample project to me? @Yuuki-Ishimaru 
Here is my email sanghun.kim@bhaptics.com

**Comment by SanghunK** [comment]
Well, sadly, the sample you sent works well for me. I can't reproduce this issue.
I don't think it's a Unity SDK issue. As you said, it seems to be a problem with bHaptics Player, but this is also ambiguous because you updated it well.
So, could you tell me your Windows version? (you can check it running "winver")

+ Is there any other issue except IsConnect? Does it vibrate?

**Comment by SanghunK** [comment]
Oh, wow. Your Windows version is so old.
Is there any reason why you don't update? If you don't mind, please update and try again.
We use Bluetooth on Windows, so the version may be the reason!

**Comment by Yuuki-Ishimaru** [comment]
What version of windows should be used?

**Comment by westside** [comment]
Hi, @Yuuki-Ishimaru  sorry for the issue. 
Can you play the same project to the other computer if possible?

**Comment by SanghunK** [comment]
That's a good news!
I'm so glad the problem has been solved, and please feel free to let me know if you have any other problems.
Thank you!


-This issue will be closed.
