### ISSUE TITLE
Possibly migrate new/delete to unique_ptr for exception safety

### ISSUE THREAD

**Issue by wmcnamara** [bhaptics/haptic-library#201]
Hello! 

In the haptics library cpp file I noticed that in a few spots that use raw new and delete to manage local buffers, like in the example below.

https://github.com/bhaptics/haptic-library/blob/61c535a804c489503218a40a25fd828dad1d8307/src/HapticLibrary.cpp#L43-L47

This issue simply suggests that at some point these could be migrated to use unique_ptr, because if `WideCharToMultiByte`, the `std::string` constructor, or any code in the future between the new/delete threw an exception, it would cause a memory leak.

I would be willing to run through and submit a PR tp change these to use unique_ptr aswell if you would like. Let me know if that is something you are interested in.

Thanks!

**Comment by SanghunK** [comment]
Hi! @wmcnamara

First of all, Thank you so much for letting me know about this issue.
As you said, would you submit a PR?
I want to know your solution. Thank you.

**Comment by wmcnamara** [comment]
Sure, ill go ahead and do that!
