### ISSUE TITLE
[비햅틱스 SDK 문의] Bhaptics studio에 관한 질문입니다.

### ISSUE THREAD

**Issue by kjw8515** [bhaptics/haptic-library#204]
작년에 비햅틱스 장비를 저희 연구실에서 구매하여 사용하고 있는데 궁금한 점이 있어 메일을 드리게 되었습니다.

Bhaptics studio에서 설정한 옵션(Threshold와 특정 주파수 On/Off, 특정 주파수에서 슈트 진동 활성화 )에 맞게 유니티에서 음악/소리 제공 시, 실시간 진동 피드백 설정하도록 하고 싶습니다. Bhaptics studio에 Export가 있어 파일을 받았지만 어떻게 사용하는 지 모르겠습니다. 유니티 내에서 음악에 맞는 진동을 제공하고 싶은데 사용법을 알려주실 수 있으실까요? 

또, BhapticsTargetCharacter 프리펩에서 슈트모양에 Box collider가 중첩되면, 진동 피드백이 발생하게 디자인이 가능한 걸로 알고 있습니다. 특정 진동자를 활성화하기 위한 command code나 함수를 알려주실 수 있으신가요?

스크립트를 찾아봤지만 찾기가 어렵네요. 

알려주시면 감사드립니다.

좋은 하루 되세요~

**Comment by second141** [comment]
## 1. Bhaptics Studio 사용방법
audio to haptic 설정 파일은 따로 export / import 하실 필요 없습니다.

스튜디오에서 추가/수정한 audio to haptic 테마가 자동으로 **bHaptics Player**에 추가되며,
플레이어에서 audio to haptic 설정을 켜시고, 테마만 변경해주신 다음
음악, 소리가 재생되면 실시간 진동 피드백이 동작합니다.

아래 사진 참고 부탁드립니다

![1 BhapticsStudio-ATH](https://user-images.githubusercontent.com/15921608/163936248-7f14ba73-88f1-44d5-aa07-2b772a1b115a.png)

---
Audio To Haptic 기능은 **오디오 재생장치의 볼륨**에 영향을 받습니다.
현재 **bHaptics Player**의 **Playback Device**로 설정된 장치의 볼륨이 작거나, 음소거 되어있는 상태에서는
Audio To Haptic 기능이 켜져있어도 진동 피드백이 오지 않으니 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/15921608/163936776-7987737a-287a-4384-a0f6-f49006867126.png)
---
## 2. BhapticsTargetCharacter 프리팹 충돌시 진동피드백 발생방법
Unity SDK상에서 제공해드리는 데모 씬으로 문의주신 내용 확인 가능합니다.
데모 씬 경로 : **Assets/Bhaptics/SDK/Examples/Scenes/7_Demo_Shooter**

위 데모씬에서 말씀해주신 **BhapticsTargetCharacter**에 장착된 기기 모델을 보시면 **HapticReceiver** 컴포넌트가 추가되어있고
플레이어 캐릭터 혹은 배치된 **BhapticsShootingCharacter** 가 발사한 총알에는 **HapticSender** 컴포넌트가 추가되어 있습니다.

두 물체가 서로 충돌했을 때 맞은 부위(기기)에 따라
**HapticSender**에 미리 등록해둔 햅틱 피드백 패턴이 재생되는 방식으로 구현되어있는 샘플입니다.

자세한 내용은 두 스크립트를 참고하시면 될것 같습니다. 

![2-1 충돌시 햅틱피드백 예시](https://user-images.githubusercontent.com/15921608/163937469-5615febd-e9a1-484e-8c10-f0c51296818a.png)
---

---
추가로 문의주신 특정 진동자를 활성화하는 방법도 마찬가지로
Unity SDK상에서 제공해드리는 데모 씬으로 확인 가능합니다. 
데모 씬 경로 : **Assets/Bhaptics/SDK/Examples/Scenes/6_DotPoint_via_script**

아래 첨부한 이미지와 **BhapticsDotPointExample.cs, BhapticsDotPointControllerExample.cs** 스크립트를 참고하시면 될것 같습니다.

![2-2 특정진동자 활성 예시](https://user-images.githubusercontent.com/15921608/163937642-259327c2-9646-45a8-ad74-763debb63230.png)

**Comment by kjw8515** [comment]
추가로 

ClipPositionType의 경우, Vest Front 및 Vest Back 등의 종류가 있는 걸로 보입니다.
Vest Front와 Vest Back을 동시에 Dotpoint로 진동을 주고 싶은데 같이 틀 경우, 둘 중에 하나만 진동이 활성화 되는 것 같네요. 
두 type 모두에 진동을 줄 수 있는 방법이 있을까요?

**Comment by kjw8515** [comment]
> ## 1. Bhaptics Studio 사용방법
> audio to haptic 설정 파일은 따로 export / import 하실 필요 없습니다.
> 
> 스튜디오에서 추가/수정한 audio to haptic 테마가 자동으로 **bHaptics Player**에 추가되며, 플레이어에서 audio to haptic 설정을 켜시고, 테마만 변경해주신 다음 음악, 소리가 재생되면 실시간 진동 피드백이 동작합니다.
> 
> 아래 사진 참고 부탁드립니다
> 
> ![1 BhapticsStudio-ATH](https://user-images.githubusercontent.com/15921608/163936248-7f14ba73-88f1-44d5-aa07-2b772a1b115a.png)
> 
> Audio To Haptic 기능은 **오디오 재생장치의 볼륨**에 영향을 받습니다. 현재 **bHaptics Player**의 **Playback Device**로 설정된 장치의 볼륨이 작거나, 음소거 되어있는 상태에서는 Audio To Haptic 기능이 켜져있어도 진동 피드백이 오지 않으니 확인 부탁드립니다.
> 
> ## ![image](https://user-images.githubusercontent.com/15921608/163936776-7987737a-287a-4384-a0f6-f49006867126.png)
> ## 2. BhapticsTargetCharacter 프리팹 충돌시 진동피드백 발생방법
> Unity SDK상에서 제공해드리는 데모 씬으로 문의주신 내용 확인 가능합니다. 데모 씬 경로 : **Assets/Bhaptics/SDK/Examples/Scenes/7_Demo_Shooter**
> 
> 위 데모씬에서 말씀해주신 **BhapticsTargetCharacter**에 장착된 기기 모델을 보시면 **HapticReceiver** 컴포넌트가 추가되어있고 플레이어 캐릭터 혹은 배치된 **BhapticsShootingCharacter** 가 발사한 총알에는 **HapticSender** 컴포넌트가 추가되어 있습니다.
> 
> 두 물체가 서로 충돌했을 때 맞은 부위(기기)에 따라 **HapticSender**에 미리 등록해둔 햅틱 피드백 패턴이 재생되는 방식으로 구현되어있는 샘플입니다.
> 
> 자세한 내용은 두 스크립트를 참고하시면 될것 같습니다.
> 
> ## ![2-1 충돌시 햅틱피드백 예시](https://user-images.githubusercontent.com/15921608/163937469-5615febd-e9a1-484e-8c10-f0c51296818a.png)
> 추가로 문의주신 특정 진동자를 활성화하는 방법도 마찬가지로 Unity SDK상에서 제공해드리는 데모 씬으로 확인 가능합니다. 데모 씬 경로 : **Assets/Bhaptics/SDK/Examples/Scenes/6_DotPoint_via_script**
> 
> 아래 첨부한 이미지와 **BhapticsDotPointExample.cs, BhapticsDotPointControllerExample.cs** 스크립트를 참고하시면 될것 같습니다.
> 
> ![2-2 특정진동자 활성 예시](https://user-images.githubusercontent.com/15921608/163937642-259327c2-9646-45a8-ad74-763debb63230.png)

감사합니다. 

추가로

ClipPositionType의 경우, Vest Front 및 Vest Back 등의 종류가 있는 걸로 보입니다.
Vest Front와 Vest Back을 동시에 Dotpoint로 진동을 주고 싶은데 같이 틀 경우, 둘 중에 하나만 진동이 활성화 되는 것 같네요.
두 type 모두에 진동을 줄 수 있는 방법이 있을까요?
