### ISSUE TITLE
BhapticsDotPointControllerExample.cs의 ClipPositionType에 관한 질문입니다.

### ISSUE THREAD

**Issue by kjw8515** [bhaptics/haptic-library#207]
BhapticsDotPointControllerExample.cs에서
ClipPositionType의 경우, Vest Front 및 Vest Back 등의 종류가 있는 걸로 보입니다.
Vest Front와 Vest Back을 동시에 Dotpoint로 진동을 주고 싶은데 같이 틀 경우, 둘 중에 하나만 진동이 활성화 되는 것 같네요.
두 type 모두에 진동을 줄 수 있는 방법이 있을까요?

**Comment by SanghunK** [comment]
네 물론 있습니다.
둘 중 하나만 진동이 울리는 이유는 key가 같아서 기존에 울리던 햅틱과 새로이 울린 햅틱이 같은것이라 인식하여 그렇습니다.
고로 key를 다르게 넣어서 불러주시면 됩니다. 5_Identifier_Play 샘플씬을 참고하시면 도움이 되실겁니다.

추가로 key는 햅틱의 이름이라고 생각하시면 되는데, 햅틱을 울리기만 하고 도중에 중지할 일이 없으시면 랜덤한 값으로 보내셔도 무관합니다.

**Comment by kjw8515** [comment]
> 네 물론 있습니다. 둘 중 하나만 진동이 울리는 이유는 key가 같아서 기존에 울리던 햅틱과 새로이 울린 햅틱이 같은것이라 인식하여 그렇습니다. 고로 key를 다르게 넣어서 불러주시면 됩니다. 5_Identifier_Play 샘플씬을 참고하시면 도움이 되실겁니다.
> 
> 추가로 key는 햅틱의 이름이라고 생각하시면 되는데, 햅틱을 울리기만 하고 도중에 중지할 일이 없으시면 랜덤한 값으로 보내셔도 무관합니다.

감사합니다 !! 

한 가지 더 문의드리자면, Audio to tactile은 모드를 변경하면 소리에 따른 진동 피드백을 제공하는 것을 확인했습니다.
하지만, 유니티 상에서 특정 시간이나 이벤트에서 audio to tactile 모드를 on/off control 하고 싶습니다. Bhaptics Player 프로그램에서 모드 변경을 하는 것 말고 유니티에서 명령에 의해 audio to tactile 모드를 on/off할 수 있는 방법이 있나요?
