### ISSUE TITLE
[Unity-Android] Pairing Issue on Oculus Quest

### ISSUE THREAD

**Issue by SanghunK** [bhaptics/haptic-library#79]
1. 게임(페인트볼 모바일)을 종료하고 재실행시 자동으로 기기가 페어링되는것이 꽤나 느림(약 30초 기다려야함) - 정확한 현상은 기기에는 불빛이 들어왔으나 게임상에선 연결이 안된것으로 표시됨 + 핑도 안됨
2. 연결이 되더라도 핑이 늘어지는 경우가 종종 있음. 그럴땐 언페어하고 다시 페어해야함
3. 1번과 같은 이슈는 연결하는 기기의 수가 많아질수록 더 빈번해짐(4개일땐 3~4번에 1번정도)

**Comment by westside** [comment]
SDK version: 1.4.7 
when more than 3 devices are paired. 

1. Sometimes devices are actually connected but UI does not recognize it.
 It recovers about 30 seconds later. 
2. ping is very slow and not working sometimes 
3. it's getting worse when number of paired devices increases.
